# This is a basic workflow to help you get started with Actions

name: Arduino Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: Run arduino-builder
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
      # Path to a single sketch
      sketch: # optional
      # Directory in which to search for sketches
      sketchDirectory: # optional, default is examples
      # Fully Qualified Board Name
      board: # optional, default is arduino:avr:uno
      # Directory containing Arduino libraries
      libraries: # optional, default is libraries
      # Directory containing Arduino platforms
      hardware: # optional, default is hardware
