# This is a basic workflow to help you get started with Actions

name: Arduino Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master
    - name: Build for OSV
      uses: ArminJo/arduino-test-compile@v2.0.0
      with:
        path: OpenSourceVentilator
        arduino-board-fqbn: arduino:avr:nano
        arduino-platform: arduino:avr@1.8.2
        required-libraries: AccelStepper,LiquidCrystal_PCF8574,jm_Wire,BME280,TimerOne
        sketch-names: OpenSourceVentilator.ino
      
